version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: cas-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: cas-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: postgres:16
    container_name: cas-postgres
    environment:
      POSTGRES_DB: currency_alert_db
      POSTGRES_USER: cas_user
      POSTGRES_PASSWORD: cas_pass
      TZ: UTC
    ports:
      - "15432:5432"
    volumes:
      - cas_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cas-redis
    ports:
      - "6379:6379"

volumes:
  cas_pg_data: